### ISSUE TITLE
Postman local app don't recognize JSON file.

### ISSUE THREAD

**Issue by SemaphoreOxalis** [alexandreelise/j4x-api-collection#42]
**Describe the bug**
Json file can't be imported in postman app

**Comment by alexandreelise** [comment]
Hello @SemaphoreOxalis you can use the run in postman button and follow the instructions to import the collection in your postman local app. One side note too. Make sure you use the latest version of the app and the collection. Have a great day. Happy coding.

**Comment by SemaphoreOxalis** [comment]
I know we can fork the collection or copy/paste raw data but the issue is about the json file which have an issue and send an error in import. If someone just try the json he would be blocked.

**Comment by alexandreelise** [comment]
> I know we can fork the collection or copy/paste raw data but the issue is about the json file which have an issue and send an error in import. If someone just try the json he would be blocked.

Hi @SemaphoreOxalis. My piece of advise is to use the Run in postman button and fork the collection rather than trying to do it manually.
