### ISSUE TITLE
Add filters for content/articles

### ISSUE THREAD

**Issue by ThibautMilville** [alexandreelise/j4x-api-collection#53]
I recently discovered that the /content/articles endpoint supports filtering by parameters such as category, state or search term, which isn't mentioned in the documentation. For example, you can use:

/content/articles?filter[category]=10 to filter articles by category 10.
/content/articles?filter[category]=10&filter[state]=1 to filter articles by category 10 and published state
/content/articles?filter[language]=en-GB&filter[state]=1 to filter articles by language and published state
/content/articles?filter[search]=tavern to search for articles containing the term "tavern".

Would it be possible to include this filtering capability in the documentation so that others can easily find and use it? It would significantly improve the efficiency of navigating and retrieving specific articles.

**Comment by garstud** [comment]
Nice @ThibautMilville ! ... And hello @alexandreelise  ;) 
I just tested this, it's great!

In fact, the API filter seems to work almost* like the **Joomla backend filters**!  
(*the filter names are not quite equivalent: published=>state, ...)

So on the articles we have these filters:  
![image](https://github.com/user-attachments/assets/96c0dbed-a8db-402d-82e4-4d6b2668c267)

And in particular for the "**Tags**" filter which is multi-value, it works using the following API filter (3,22,18 and 7 are my tag IDs):  
/api/index.php/v1/content/articles?filter[tag]=3,22,18,7  
Like in Backend filters: 
![image](https://github.com/user-attachments/assets/91b73488-b7cd-46c8-a868-256343aa1c20)

I did not find any information in the documentation on these filters:
- https://manual.joomla.org/docs/web-services-api/ ?
- https://docs.joomla.org/Main_Page
- just an issue that deals with a similar subjet on filtering by alias : https://github.com/joomla/joomla-cms/issues/42503

**Comment by woluweb** [comment]
Hi everyone,

You can see this presentation I made some time ago about, in particular this section `Filter, Search and Order the Articles you are fetching via the API`:

https://slides.woluweb.be/api/api.html#filter-search-and-order-the-articles-you-are-fetching-via-the-api

See in particular this source file which lists all possibilities

https://github.com/joomla/joomla-cms/blob/5.2-dev/api/components/com_content/src/Controller/ArticlesController.php#L54 and following (for example Line 65 for Search, Line 85 for List)

**Comment by garstud** [comment]
Perfect @woluweb thanks for sharing ;) 

Maybe you can add the **multi-value tag example** to your slides?

Thanks for the controller link, i have already get a look in this source ;)

**Comment by woluweb** [comment]
> Maybe you can add the **multi-value tag example** to your slides?
> 
> Thanks for the controller link, i have already get a look in this source ;)

Good idea: I have created a new little section about multivalue: https://slides.woluweb.be/api/api.html#multivalue

And I also took the opportunity to update the 3 links to the controller (was mentioning 5.0-dev while the current version has now become 5.2-dev of course).
